spring:
  application:
    name: QrCodeGenerator

  datasource:
    url: jdbc:postgresql://dpg-d59atq2li9vc73ahjj30-a.oregon-postgres.render.com:5432/qrcode_azxq
    username: admin
    password: ZlcB8NxoiHq9oOyTWzm8gWGNoLQmSOYr
    driver: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enable: true
    locations: classpath:db/migration
