spring:
  application:
    name: QrCodeGenerator

  datasource:
    url: jdbc:postgresql://dpg-d55vebmuk2gs73c6tt30-a.oregon-postgres.render.com:5432/eventclean
    username: admin
    password: fAl9Ja98449OHT0sMCqCkwONpxCzhHox
    driver: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enable: true
    locations: classpath:db/migration
